### ISSUE TITLE
How does this package work?

### ISSUE THREAD

**Issue by chaoyue729** [xiaket/Snape#1]
Does it have demo code and how it use in jupyter-notebook

**Comment by xiaket** [comment]
Hi!

I do not work in ML and big data, so jupyter is not in my toolbox, but I believe the usage pattern would be:

1. Install `Snape` using `pip`.
2. From `Files`, use the dropdown menu on the right to start a new Terminal.
3. Run Snape in the new terminal window, for example, `Snape add test snippet`.

P.S. I've updated the README file, hope that will also be of help to you.

**Comment by xiaket** [comment]
closing.
